version: '3.2'

services:

  # ==================
  # command line tools
  # ==================

  tools:
    build:
      context: tools
    container_name: tools
    volumes:
      - ./shared:/shared

  # ==================
  # InterSystems IRIS
  # ==================

  # irisA instance
  irisA:
    build:
      context: .
      args:
        WEBINAR_INCLUDE_API: "no"
    container_name: irisA
    command: --check-caps false
    image: workshop-rest-iam:noapi
    ports:
    - "52773:52773"
    volumes:
    - ./iris.key:/usr/irissys/mgr/iris.key
    - ./shared:/shared

  # irisB instance  
  irisB:
    build:
      context: .
      args:
        WEBINAR_INCLUDE_API: "yes"
    image: workshop-rest-iam:api
    container_name: irisB
    command: --check-caps false
    ports:
    - "52774:52773"
    volumes:
    - ./iris.key:/usr/irissys/mgr/iris.key
    - ./shared:/shared

  # irisC instance 
  irisC:
    build:
      context: .
      args:
        WEBINAR_INCLUDE_API: "yes"
    image: workshop-rest-iam:api
    container_name: irisC
    command: --check-caps false
    ports:
    - "52775:52773"
    volumes:
    - ./iris.key:/usr/irissys/mgr/iris.key
    - ./shared:/shared

  # ====================================
  # IAM - InterSystems API Manager 2.3.3
  # ====================================
  iam-migrations:
    image: "${ISC_IAM_IMAGE}"
    command: kong migrations bootstrap
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-iam}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      KONG_PG_USER: ${KONG_PG_USER:-iam}
      KONG_CASSANDRA_CONTACT_POINTS: db
      ISC_IRIS_URL: "${ISC_IRIS_URL}"
      ISC_CA_CERT: "${ISC_CA_CERT}"
    restart: on-failure
    links:
      - db:db
  iam:
    image: "${ISC_IAM_IMAGE}"
    depends_on:
      - db
      - irisA
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_ANONYMOUS_REPORTS: 'off'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-iam}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      KONG_PG_USER: ${KONG_PG_USER:-iam}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PORTAL: 'on'
      KONG_PORTAL_GUI_PROTOCOL: http
      KONG_PORTAL_GUI_HOST: '127.0.0.1:8003'
      KONG_ADMIN_GUI_URL: http://localhost:8002
      #KONG_ENFORCE_RBAC: 'on'
      #KONG_ADMIN_GUI_AUTH: basic-auth
      #KONG_ADMIN_GUI_SESSION_CONF: '{"cookie_name":"iam-admingui", "secret":"change-this-secret","storage":"kong","cookie_secure":false}'
      ISC_IRIS_URL: "${ISC_IRIS_URL}"
      ISC_CA_CERT: "${ISC_CA_CERT}"
    links:
      - db:db
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 8001
        published: 8001
        protocol: tcp
      - target: 8002
        published: 8002
        protocol: tcp
      - target: 8003
        published: 8003
        protocol: tcp
      - target: 8004
        published: 8004
        protocol: tcp
      - target: 8443
        published: 8443
        protocol: tcp
      - target: 8444
        published: 8444
        protocol: tcp
      - target: 8445
        published: 8445
        protocol: tcp
    restart: on-failure
  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-iam}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      POSTGRES_USER: ${KONG_PG_USER:-iam}
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-iam}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
volumes:
  pgdata:
