version: '3.2'

services:
  
  # cmd line tools 
  tools:
    build:
      context: tools
    container_name: tools
    volumes:
      - ./shared:/shared
    networks:
      - iam-network

  # irisA instance
  irisA:
    build:
      context: .
      args:
        WEBINAR_INCLUDE_API: "no"
    container_name: irisA
    command:
      --key /app/iris.key
    image: workshop-rest-iam:noapi
    ports:
    - "52773:52773"
    volumes:
    - .:/app
    - ./shared:/shared
    networks:
      - iam-network

  # irisB instance  
  irisB:
    build:
      context: .
      args:
        WEBINAR_INCLUDE_API: "yes"
    image: workshop-rest-iam:api
    container_name: irisB
    command:
      --key /app/iris.key
    ports:
    - "52774:52773"
    volumes:
    - .:/app
    - ./shared:/shared
    networks:
    - iam-network

  # irisC instance 
  irisC:
    build:
      context: .
      args:
        WEBINAR_INCLUDE_API: "yes"
    image: workshop-rest-iam:api
    container_name: irisC
    command:
      --key /app/iris.key
    ports:
    - "52775:52773"
    volumes:
    - .:/app
    - ./shared:/shared
    networks:
      - iam-network

networks:
  iam-network:
    name: iam-network